### ISSUE TITLE
按键设置为全透明后崩溃

### ISSUE THREAD

**Issue by PickLeaf** [Tungstend/HMCL-PE#109]
将一个按键的填充色改为"#1ffffff"，点完成，崩溃。

机型：红米note10pro
系统：MIUI13.0.8.0（稳定版）

Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-10-25 15:50:53 
Device: Xiaomi M2104K10AC 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.IllegalArgumentException: Unknown color
	at android.graphics.Color.parseColor(Color.java:1390)
	at com.tungsten.hmclpe.launcher.dialogs.tools.ColorSelectorDialog.onEditorAction(ColorSelectorDialog.java:132)
	at android.widget.TextView.onEditorAction(TextView.java:7162)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:159)
	at android.view.inputmethod.InputConnectionWrapper.performEditorAction(InputConnectionWrapper.java:228)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:577)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:111)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8268)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by PickLeaf** [comment]
设置颜色的文本框会剔除颜色代码首位的0，可以用"#10ffffff"就不会出错了，只不过不是纯透明的
