### ISSUE TITLE
Bug on execution

### ISSUE THREAD

**Issue by Paul75** [Tungstend/HMCL-PE#111]
**Describe the bug**
When play crash.

<summary>log file name</summary>

```
Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-10-26 09:41:28 
Device: HUAWEI NOH-NX9 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tungsten.hmclpe/com.tungsten.hmclpe.launcher.launch.boat.BoatMinecraftActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.tungsten.hmclpe.launcher.setting.launcher.LauncherSetting.gameFileDirectory' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.tungsten.hmclpe.launcher.setting.launcher.LauncherSetting.gameFileDirectory' on a null object reference
	at com.tungsten.hmclpe.launcher.setting.game.GameLaunchSetting.getGameLaunchSetting(GameLaunchSetting.java:77)
	at com.tungsten.hmclpe.launcher.launch.boat.BoatMinecraftActivity.onCreate(BoatMinecraftActivity.java:48)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
	... 11 more

```
</details>

**Comment by Paul75** [comment]
Hello

And when save ans after suit And want to restant saved it load ans after progression start quit the game....
