### ISSUE TITLE
when i tap the screen it instant crashes any fix?

### ISSUE THREAD

**Issue by 1E0CODE** [Tungstend/HMCL-PE#20]
when launching any version it instant crashes when i tap the screen

**Paste logs here**
```

java.lang.NumberFormatException: For input string: "2.0"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.tungsten.hmclpe.control.view.TouchPad.onTouchEvent(TouchPad.java:157)
	at android.view.View.dispatchTouchEvent(View.java:14673)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:690)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1971)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4383)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:642)
	at android.view.View.dispatchPointerEvent(View.java:14945)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6738)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6504)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5961)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6028)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5989)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6162)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5997)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6219)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5965)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6028)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5989)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5997)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5965)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9044)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8995)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8955)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9179)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:276)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8278)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

```

**Smartphone (please complete the following information):**
 - Device: [Vivo V2046/Vivo x60]
 - OS: [Android 12 (SDK 31)]
 - Version [1.0.0]

**Comment by MatheusTGamerPro** [comment]
did you put any custom java path? what is the name of your instance of the Game?
