### ISSUE TITLE
Crash 🗿🗿🗿🗿

### ISSUE THREAD

**Issue by NSTAdventure** [Tungstend/HMCL-PE#22]
**Describe the bug**

**To Reproduce**
1. Open HLMC PE download Mc version 1.7.10 and latest Minecraft forge with optifine
2. Open mc and create world
3. Play for a while
4. HLMC PE either will lagging or crashed

**Paste logs here**
Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-09-02 13:52:24 
Device: Realme RMX2030 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1136)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
	at com.tungsten.hmclpe.skin.utils.Avatar.lambda$setAvatar$1(Avatar.java:32)
	at com.tungsten.hmclpe.skin.utils.Avatar$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:899)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

**Expected behavior**
Work

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Realme 5i
 - OS: Android 10
 - Version: pre release

**Additional context**
All setting included from optifine is setup low end as possible

**Comment by LegacyGamerHD** [comment]
pre release isnt a version
