### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 2045632193** [Tungstend/HMCL-PE#8]
在安装1.19.2时下载资源文件那一步会崩溃

**Comment by 2045632193** [comment]
崩溃日志:
Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-08-29 03:36:27 
Device: Vivo V1813T 
OS version: Android 8.1.0 (SDK 27) 
 
Stack trace:  
java.lang.RuntimeException: javax.net.ssl.SSLException: Unable to create application data
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.newSsl(ConscryptFileDescriptorSocket.java:161)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.<init>(ConscryptFileDescriptorSocket.java:152)
	at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:149)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:181)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
	at com.tungsten.hmclpe.task.DownloadTask.downloadFileMonitored(DownloadTask.java:180)
	at com.tungsten.hmclpe.utils.io.DownloadUtil.lambda$downloadMultipleFiles$3(DownloadUtil.java:77)
	at com.tungsten.hmclpe.utils.io.DownloadUtil$$ExternalSyntheticLambda3.run(Unknown Source:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLException: Unable to create application data
	at com.android.org.conscrypt.NativeCrypto.SSL_new(Native Method)
	at com.android.org.conscrypt.SslWrapper.newInstance(SslWrapper.java:58)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.newSsl(ConscryptFileDescriptorSocket.java:159)
	... 20 more

**Comment by mcagabe19** [comment]
minecraft 1.17+ broken

**Comment by LegacyGamerHD** [comment]
> minecraft 1.17+ broken

Nah works fine
