### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by VladRobo** [Tungstend/HMCL-PE#96]
Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-10-10 04:48:56 
Device: Samsung SM-A217F 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.IllegalArgumentException: Unknown color
	at android.graphics.Color.parseColor(Color.java:1390)
	at com.tungsten.hmclpe.launcher.MainActivity$1.handleMessage(MainActivity.java:131)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by VladRobo** [comment]
Неизвестный цвет. Я хотел зделать прозрачную панель.

**Comment by MatheusTGamerPro** [comment]
I saw in the code and the ```parseColor()``` is not checking if the color is valid or not, this may be fixed soon.

**Comment by MatheusTGamerPro** [comment]
> Build version: 1.0.0 Build date: 1981-01-01 01:01:02 Current date: 2022-10-10 04:48:56 Device: Samsung SM-A217F OS version: Android 12 (SDK 31)
> 
> Stack trace: java.lang.IllegalArgumentException: Unknown color at android.graphics.Color.parseColor(Color.java:1390) at com.tungsten.hmclpe.launcher.MainActivity$1.handleMessage(MainActivity.java:131) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at android.app.ActivityThread.main(ActivityThread.java:8669) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

What was the color code you put in?

**Comment by VladRobo** [comment]
I do not remember.  most likely 0. I wanted to make a transparent interface and this error appeared when I tried to make a transparent button.  Sorry for not answering for a long time.
